<?
$aMenuLinks = Array(
    Array(
        "О компании",
        "/company/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Референс-объекты",
        "/integrated-solutions/all_projects.php",
        Array(),
        Array(),
        ""
    ),
	Array(
		"Контакты",
		"/contacts/tsentralnyy-ofis-khogart-v-moskve-sklad-i-servisnaya-sluzhba/",
		Array(), 
		Array(),
		"" 
	),
	Array(
		"Отзывы",
		"/company/comments/",
		Array(),
		Array(),
		""
	)
);
?>