<?php
/**
 * Created by PhpStorm.
 * User: Ivan Koretskiy aka gillbeits[at]gmail.com
 * Date: 11/07/16
 * Time: 00:51
 */

namespace Sprint\Migration;


use Sprint\Migration\Helpers\IblockHelper;

class Version201607110001 extends Version
{
    protected $description = "Задача HG-33: работа с блоком Комплексные решения";

    public function up()
    {
        $blockId = 18;
        $iBlockHelper = new IblockHelper();
        $iBlockHelper->updatePropertyIfExists($blockId, "problem", array_merge($iBlockHelper->getProperty($blockId, "problem"), [
            "NAME" => "Описание",
            "CODE" => "description"
        ]));
        $iBlockHelper->deletePropertyIfExists($blockId, "prop_proj");
        $iBlockHelper->deletePropertyIfExists($blockId, "prop_proj_int");
        $iBlockHelper->deletePropertyIfExists($blockId, "solution_project");
        $iBlockHelper->deletePropertyIfExists($blockId, "goods");

        $iBlockHelper->addPropertyIfNotExists($blockId, [
            "NAME" => "Оборудование",
            "CODE" => "infographics",
            "MULTIPLE" => "Y",
            "WITH_DESCRIPTION" => "Y",
            "PROPERTY_TYPE" => "F",
            "FILE_TYPE" => "jpg, gif, bmp, png, jpeg"
        ]);

        \CUserOptions::DeleteOptionsByName("form", "form_element_" . $blockId);
        \CUserOptions::SetOption("form", "form_element_" . $blockId, [
            "tabs" => "edit1--#--Элемент--,--ACTIVE--#--Активность--,--ACTIVE_FROM--#--Начало активности--,--ACTIVE_TO--#--Окончание активности--,--NAME--#--*Название--,--CODE--#--*Символьный код--,--DETAIL_PICTURE--#--Основное изображение--,--DETAIL_TEXT--#--Адрес--,--SORT--#--Сортировка--,--IBLOCK_ELEMENT_PROP_VALUE--#----Значения свойств--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "zones") . "--#--Участие в категории проектов--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "description") . "--#--Описание--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "video") . "--#--Видео--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "photogallery") . "--#--Фотогалерея--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "solution_id") . "--#--Комплексное решение--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "infographics") . "--#--Оборудование (инфографика)--;--cedit1--#--Отзыв--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "review_photo") . "--#--Фото--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "review_author") . "--#--Имя автора--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "review_author_status") . "--#--Должность автора--,--PROPERTY_" . $iBlockHelper->getPropertyId($blockId, "review_text") . "--#--Отзыв--;--"
        ], true);

    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }

}