<?php
/**
 * Created by PhpStorm.
 * User: Ivan Koretskiy aka gillbeits[at]gmail.com
 * Date: 01/07/16
 * Time: 11:26
 */

namespace Sprint\Migration;


use Sprint\Migration\Helpers\IblockHelper;

class Version201607010001 extends Version
{
    public function up()
    {
        $detail_text =<<<HTML
Компания имеет&nbsp;собственный офисно-складской комплекс, два салона розничных продаж в Москве и офисно-складской комплекс в Санкт-Петербурге.
HTML;
        $partners_text =<<<HTML
<p>Профессионалы отрасли и стремящиеся ими стать монтажные, строительные, проектные и инжиниринговые компании, архитектурные и дизайнерские бюро.
</p>
<h4>Наши прайс-листы:</h2>
<ul>
	<li>
	<p>
 <a title="Hogart_Otoplenie_all_web!.pdf" href="http://dev.hogart.ru/upload/medialibrary/70d/Hogart_Otoplenie_all_web!.pdf"><i class="fa fa-download"></i> ОТОПЛЕНИЕ</a>
	</p>
 </li>
	<li>
	<p>
 <a title="Прайс-лист (вентиляция)" href="http://dev.hogart.ru/upload/medialibrary/e72/VENT_all_2015_web.pdf"><i class="fa fa-download"></i> ВЕНТИЛЯЦИЯ</a>
	</p>
 </li>
	<li>
	<p>
 <a title="Прайс-лист (сантехника)" href="http://dev.hogart.ru/upload/medialibrary/072/katalog_II_2015_web_new.pdf"><i class="fa fa-download"></i> САНТЕХНИКА</a>
	</p>
 </li>
</ul>
HTML;


        \CModule::IncludeModule("iblock");
        \CIBlockElement::Update("21", [
            "DETAIL_TEXT" => $detail_text,
            "PROPERTY_VALUES" => [
                "partners" => $partners_text
            ]
        ]);
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }
}
