<?php
/**
 * Created by PhpStorm.
 * User: Ivan Koretskiy aka gillbeits[at]gmail.com
 * Date: 07/07/16
 * Time: 19:43
 */

namespace Sprint\Migration;


use Sprint\Migration\Helpers\IblockHelper;

class Version201607070001 extends Version
{
    public function up()
    {
        $iBlockHelper = new IblockHelper();
        if ($iBlockHelper->deletePropertyIfExists(5, "partners")) {
            $this->outSuccess("Удалено свойство \"Партнеры\" блока \"Компания\"");
        }
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }

}