<?php
/**
 * Created by PhpStorm.
 * User: Ivan Koretskiy aka gillbeits[at]gmail.com
 * Date: 09/07/16
 * Time: 12:50
 */

namespace Sprint\Migration;


use Sprint\Migration\Helpers\IblockHelper;

class Version201607090001 extends Version
{
    protected $description = "Обновление инфо-блока Бренды";
    public function up()
    {
        $iBlockHelper = new IblockHelper();
        try {
            $photoFields = $iBlockHelper->getProperty(2, "photogallery");
            $iBlockHelper->updatePropertyIfExists(2, "photogallery", array_merge($photoFields, [
                "NAME" => "Фотогалерея - О Компании",
                "CODE" => "photogallery_about_company"
            ]));
            $iBlockHelper->addPropertyIfNotExists(2, array_merge($photoFields, [
                "NAME" => "Фотогалерея - О продуктах и решениях",
                "CODE" => "photogallery_about_products"
            ]));
        } catch (\Exception $e) {}
        
        try {
            $videoFields = $iBlockHelper->getProperty(2, "videogallery");
            $iBlockHelper->updatePropertyIfExists(2, "videogallery", array_merge($videoFields, [
                "NAME" => "Видеогалерея - О Компании",
                "CODE" => "videogallery_about_company"
            ]));
            $iBlockHelper->addPropertyIfNotExists(2, array_merge($videoFields, [
                "NAME" => "Видеогалерея - О продуктах и решениях",
                "CODE" => "videogallery_about_products"
            ]));
        } catch (\Exception $e) {}
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }
}