<?php
/**
 * Created by PhpStorm.
 * User: Ivan Koretskiy aka gillbeits[at]gmail.com
 * Date: 10/07/16
 * Time: 13:36
 */

namespace Sprint\Migration;


use Sprint\Migration\Helpers\IblockHelper;

class Version201607100002 extends Version
{
    public function up()
    {
        $iBlockHelper = new IblockHelper();
        if (($iBlockTypeId = $iBlockHelper->addIblockTypeIfNotExists([
            'ID' => 'content',
            'SECTIONS' => 'N',
            'IN_RSS' => 'N',
            'SORT' => 100,
            'LANG' => Array(
                'ru' => Array(
                    'NAME' => 'Контент',
                    'SECTION_NAME' => 'Категории',
                    'ELEMENT_NAME' => 'Элементы'
                ),
                'en' => Array(
                    'NAME' => 'Content',
                    'SECTION_NAME' => 'Sections',
                    'ELEMENT_NAME' => 'Elements'
                ),
            )
        ]))) {
            $this->outSuccess("Добавлен тип блока \"Контент\"");
            if (($contentBlockId = $iBlockHelper->addIblockIfNotExists([
                'ACTIVE' => 'Y',
                'NAME' => 'Статичный контент',
                'CODE' => 'STATIC_CONTENT',
                'IBLOCK_TYPE_ID' => 'content'
            ]))) {
                $this->outSuccess("Добавлен инфоблок \"Статичный контент\"");
                \CUserOptions::DeleteOptionsByName("form", "form_element_" . $contentBlockId);
                \CUserOptions::SetOption("form", "form_element_" . $contentBlockId, [
                    "tabs" => "edit1--#--Элемент--,--ACTIVE--#--Активность--,--NAME--#--*Название--,--CODE--#--Символьный код--,--PREVIEW_PICTURE--#--Картинка для анонса--,--PREVIEW_TEXT--#--Описание для анонса--;--"
                ], true);
                $html =<<<HTML
В данном разделе собрана информация, которая будет Вам полезна при работе с инженерным оборудованием: генеральные каталоги, техническая информация, инструкции, пр. 
<br><br>
Если Вы не нашли то, что искали, просим написать нам на электронную почту <a href="mailto:info@hogart.ru">info@hogart.ru</a>, мы обязательно дополним раздел.
HTML;
                $iBlockHelper->addElementIfNotExists($contentBlockId, [
                    "CODE" => "documentation",
                    "NAME" => "Техническая документация",
                    "PREVIEW_TEXT" => $html,
                    "PREVIEW_TEXT_TYPE" => "html"
                ]);
            }
        }
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }
}
